from django.db import models
from django.contrib.auth.models import User



class Landlord(models.Model):
    # Links this landlord profile to a Django user account (login, password etc)
    # OneToOneField means one user can only have one landlord profile
    # CASCADE means if the user is deleted, this profile is deleted too
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='landlord_profile'
    )

    # Landlord's full name for display purposes
    name = models.CharField(max_length=255)

    # Landlord's email address, must be unique across all landlords
    email = models.EmailField(unique=True)

    phone_number = models.CharField(max_length=20)
    # The ID Nomba returns after we create a subaccount for this landlord
    # null and blank True because this gets filled AFTER registration, not during
    nomba_subaccount_id = models.CharField(
        max_length=100,
        #unique=True,
        null=True, blank=True,
    )

    # The NUBAN account number tenants send rent to
    # Generated by Nomba when we create a virtual account for this landlord
    virtual_account_number = models.CharField(
        max_length=20,
        unique=True,
        null=True, blank=True,
    )

    # The reference WE generate and pass to Nomba when creating the virtual account
    # We control this so we can look up Nomba records from our own database
    account_ref = models.CharField(
        max_length=100,
        unique=True,
        null=True, blank=True,
    )

    # The account name registered on the virtual account on Nomba's side
    account_name = models.CharField(
        max_length=255,
        null=True, blank=True,
    )

    # Automatically records when this landlord registered
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # This controls how a Landlord object displays in admin and shell
        return self.name
    

class Tenant(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name= 'tenant_profile'
    )

    name = models.CharField(max_length=255)
    email = models.EmailField(unique= True)
    phone_number = models.CharField(max_length=20)
    
    created_at = models.DateTimeField(auto_now_add=True)
     
    def __str__(self):
        return self.name
    


class Payment(models.Model):
    tenant = models.ForeignKey(
        Tenant,
        on_delete=models.CASCADE,
        related_name='tenant_payments'
    )

    landlord = models.ForeignKey(
        Landlord,
        on_delete=models.CASCADE,
        related_name='landlord_payments'
    )

    order_reference = models.CharField(
        max_length= 255,
        unique=True,
    )

    expected_amount = models.IntegerField()

    amount_received = models.IntegerField(
        null= True, blank=True,
    )

    webhook_request_id = models.CharField(
        max_length= 255,
        unique= True,
        blank=True, null=True,
    )



    class Status(models.TextChoices):
        PENDING = 'pending', 'Pending'
        CONFIRMED = 'confirmed', 'Confirmed'
        UNDERPAID = 'underpaid', 'Underpaid'
        OVERPAID = 'overpaid', 'Overpaid'
        
    status = models.CharField(
        max_length= 20,
        choices= Status.choices,
        default= Status.PENDING,
    )
        
    confirmed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.order_reference
    




class WebhookEvent(models.Model):
    request_id = models.CharField(
        max_length= 255,
        unique=True,
    )
    event_type =models.CharField(max_length=100)


    raw_payload  = models.JSONField(

    )


    signature_valid =models.BooleanField(default=False)
    

    received_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.request_id