# Generated by Django 5.2.15 on 2026-07-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='nomba_subaccount_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
